//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace ProjectSerializer
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class Import
    {

        private string projectField;

        private string labelField;

        private string conditionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class Project
    {
        private ProjectImportGroup[] importGroupField;

        private ProjectPropertyGroup[] propertyGroupField;


        private string itemDefinitionGroupField;

        private Import[] importField;

        private ProjectItemGroup[] itemGroupField;

        private string defaultTargetsField;

        private string toolsVersionField;

        /// <remarks/>
        public string ItemDefinitionGroup
        {
            get
            {
                return this.itemDefinitionGroupField;
            }
            set
            {
                this.itemDefinitionGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup")]
        public ProjectItemGroup[] ItemGroup
        {
            get
            {
                return this.itemGroupField;
            }
            set
            {
                this.itemGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup")]
        public ProjectPropertyGroup[] PropertyGroup
        {
            get
            {
                return this.propertyGroupField;
            }
            set
            {
                this.propertyGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import")]
        public Import[] Import
        {
            get
            {
                return this.importField;
            }
            set
            {
                this.importField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImportGroup")]
        public ProjectImportGroup[] ImportGroup
        {
            get
            {
                return this.importGroupField;
            }
            set
            {
                this.importGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultTargets
        {
            get
            {
                return this.defaultTargetsField;
            }
            set
            {
                this.defaultTargetsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToolsVersion
        {
            get
            {
                return this.toolsVersionField;
            }
            set
            {
                this.toolsVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroup
    {

        private ProjectItemGroupProjectConfiguration[] projectConfigurationField;

        private ProjectItemGroupNone[] noneField;

        private ProjectItemGroupClCompile[] clCompileField;

        private ProjectItemGroupClInclude[] clIncludeField;

        private string labelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("None")]
        public ProjectItemGroupNone[] None
        {
            get
            {
                return this.noneField;
            }
            set
            {
                this.noneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClCompile")]
        public ProjectItemGroupClCompile[] ClCompile
        {
            get
            {
                return this.clCompileField;
            }
            set
            {
                this.clCompileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClInclude")]
        public ProjectItemGroupClInclude[] ClInclude
        {
            get
            {
                return this.clIncludeField;
            }
            set
            {
                this.clIncludeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectConfiguration")]
        public ProjectItemGroupProjectConfiguration[] ProjectConfiguration
        {
            get
            {
                return this.projectConfigurationField;
            }
            set
            {
                this.projectConfigurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupNone
    {

        private string includeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupClCompile
    {

        private string includeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupClInclude
    {

        private string includeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupProjectConfiguration
    {

        private string configurationField;

        private string platformField;

        private string includeField;

        /// <remarks/>
        public string Configuration
        {
            get
            {
                return this.configurationField;
            }
            set
            {
                this.configurationField = value;
            }
        }

        /// <remarks/>
        public string Platform
        {
            get
            {
                return this.platformField;
            }
            set
            {
                this.platformField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectPropertyGroup
    {

        private string nMakePreprocessorDefinitionsField;

        private string nMakeIncludeSearchPathField;

        private string nMakeForcedIncludesField;

        private string nMakeAssemblySearchPathField;

        private string nMakeForcedUsingAssembliesField;

        private string includePathField;

        private string referencePathField;

        private string libraryPathField;

        private string libraryWPathField;

        private string sourcePathField;

        private string excludePathField;

        private string outDirField;

        private string intDirField;

        private string nMakeBuildCommandLineField;

        private string nMakeReBuildCommandLineField;

        private string nMakeCleanCommandLineField;

        private string nMakeOutputField;

        private string configurationTypeField;

        private string projectGuidField;

        private string keywordField;

        private string rootNamespaceField;

        private string platformToolsetField;

        private string minimumVisualStudioVersionField;

        private string targetRuntimeField;

        private string labelField;

        private string conditionField;

        /// <remarks/>
        public string NMakePreprocessorDefinitions
        {
            get
            {
                return this.nMakePreprocessorDefinitionsField;
            }
            set
            {
                this.nMakePreprocessorDefinitionsField = value;
            }
        }

        /// <remarks/>
        public string NMakeIncludeSearchPath
        {
            get
            {
                return this.nMakeIncludeSearchPathField;
            }
            set
            {
                this.nMakeIncludeSearchPathField = value;
            }
        }

        /// <remarks/>
        public string NMakeForcedIncludes
        {
            get
            {
                return this.nMakeForcedIncludesField;
            }
            set
            {
                this.nMakeForcedIncludesField = value;
            }
        }

        /// <remarks/>
        public string NMakeAssemblySearchPath
        {
            get
            {
                return this.nMakeAssemblySearchPathField;
            }
            set
            {
                this.nMakeAssemblySearchPathField = value;
            }
        }

        /// <remarks/>
        public string NMakeForcedUsingAssemblies
        {
            get
            {
                return this.nMakeForcedUsingAssembliesField;
            }
            set
            {
                this.nMakeForcedUsingAssembliesField = value;
            }
        }

        /// <remarks/>
        public string IncludePath
        {
            get
            {
                return this.includePathField;
            }
            set
            {
                this.includePathField = value;
            }
        }

        /// <remarks/>
        public string ReferencePath
        {
            get
            {
                return this.referencePathField;
            }
            set
            {
                this.referencePathField = value;
            }
        }

        /// <remarks/>
        public string LibraryPath
        {
            get
            {
                return this.libraryPathField;
            }
            set
            {
                this.libraryPathField = value;
            }
        }

        /// <remarks/>
        public string LibraryWPath
        {
            get
            {
                return this.libraryWPathField;
            }
            set
            {
                this.libraryWPathField = value;
            }
        }

        /// <remarks/>
        public string SourcePath
        {
            get
            {
                return this.sourcePathField;
            }
            set
            {
                this.sourcePathField = value;
            }
        }

        /// <remarks/>
        public string ExcludePath
        {
            get
            {
                return this.excludePathField;
            }
            set
            {
                this.excludePathField = value;
            }
        }

        /// <remarks/>
        public string OutDir
        {
            get
            {
                return this.outDirField;
            }
            set
            {
                this.outDirField = value;
            }
        }

        /// <remarks/>
        public string IntDir
        {
            get
            {
                return this.intDirField;
            }
            set
            {
                this.intDirField = value;
            }
        }

        /// <remarks/>
        public string NMakeBuildCommandLine
        {
            get
            {
                return this.nMakeBuildCommandLineField;
            }
            set
            {
                this.nMakeBuildCommandLineField = value;
            }
        }

        /// <remarks/>
        public string NMakeReBuildCommandLine
        {
            get
            {
                return this.nMakeReBuildCommandLineField;
            }
            set
            {
                this.nMakeReBuildCommandLineField = value;
            }
        }

        /// <remarks/>
        public string NMakeCleanCommandLine
        {
            get
            {
                return this.nMakeCleanCommandLineField;
            }
            set
            {
                this.nMakeCleanCommandLineField = value;
            }
        }

        /// <remarks/>
        public string NMakeOutput
        {
            get
            {
                return this.nMakeOutputField;
            }
            set
            {
                this.nMakeOutputField = value;
            }
        }

        /// <remarks/>
        public string ConfigurationType
        {
            get
            {
                return this.configurationTypeField;
            }
            set
            {
                this.configurationTypeField = value;
            }
        }

        /// <remarks/>
        public string ProjectGuid
        {
            get
            {
                return this.projectGuidField;
            }
            set
            {
                this.projectGuidField = value;
            }
        }

        /// <remarks/>
        public string Keyword
        {
            get
            {
                return this.keywordField;
            }
            set
            {
                this.keywordField = value;
            }
        }

        /// <remarks/>
        public string RootNamespace
        {
            get
            {
                return this.rootNamespaceField;
            }
            set
            {
                this.rootNamespaceField = value;
            }
        }

        /// <remarks/>
        public string PlatformToolset
        {
            get
            {
                return this.platformToolsetField;
            }
            set
            {
                this.platformToolsetField = value;
            }
        }

        /// <remarks/>
        public string MinimumVisualStudioVersion
        {
            get
            {
                return this.minimumVisualStudioVersionField;
            }
            set
            {
                this.minimumVisualStudioVersionField = value;
            }
        }

        /// <remarks/>
        public string TargetRuntime
        {
            get
            {
                return this.targetRuntimeField;
            }
            set
            {
                this.targetRuntimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectImportGroup
    {

        private Import[] importField;

        private string labelField;

        private string conditionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import")]
        public Import[] Import
        {
            get
            {
                return this.importField;
            }
            set
            {
                this.importField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import", typeof(Import))]
        [System.Xml.Serialization.XmlElementAttribute("Project", typeof(Project))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }


}